# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notes',
            new_name='note',
        ),
    ]
